# =============================================================================
# LibreRun base_config.yaml — sample_project
# =============================================================================

# Section 0 — Flow Setup
flow_setup:
    librerun_version: v0.4.RC

# Section 1 — Project Metadata
project_configuration:
    project_name: sample_project
    author: your_name
    description: Simple 4-bit counter RTL + SV testbench, LibreRun sample project

# Section 2 — Tool Configuration
tool_setup:
    verilator_base_path: /tools/verilator
    verilator_version: v5.046

# Section 3 — RTL Configuration
rtl_configuration:
    dut_top_module: counter
    rtl_source_dirs: # []
        - $PROJECT_ROOT/rtl:dut
    rtl_manual_filelists: []
        # - $PROJECT_ROOT/misc/rtl.f

# Section 4 — TB Configuration
tb_configuration:
    tb_top_module: tb_counter
    tb_source_files:
        - $PROJECT_ROOT/tb/tb_counter.sv
    tb_filelists: []
    tb_include_dirs: []
    info_keywords:
        - "[PASS]"
    warning_keywords: []
    error_keywords:
        - "[FAIL]"

# Section 5 — Compile Options
compile_options:
    defines: []
    verilator_flags: # []
        # - "-Wno-DECLFILENAME"
        - "-Wno-TIMESCALEMOD"
        - "-Wall"
    cflags:
        - "-O3"
        - "-flto=auto"
        - "-march=native"
        - "-fno-stack-protector"

# Section 6 — Simulation Options
simulation_options:
    pre_run_script: $PROJECT_ROOT/scripts/pre_run_script/test_pre_run.sh
    persistent_plusargs: []
    error_limit: 10
    seed: 0

# Section 7 — Regress Options
regression_options:
    max_parallel: 20
    keep_passing: false # Keep passing test directories (default: false)
    keep_failing: true # Keep failing test directories (default: true)
    generate_prs_logs: false
    prs_per_test: true
    prs_per_count: false

# Section 8 — Regress Suites
regression_suites:
    quick:
        default_count: 1
        tests:
            - smoke
            - basic

    all:
        default_count: 8
        tests:
            - smoke
            - basic
            - wraparound:5
            - stress:2
            - load:3
            - updown:3

    long:
        default_count: 1000
        tests:
            - smoke
            - basic
            - wraparound
            - stress
            - load
            - updown

    example:
        default_count: 5
        tests:
            - smoke
            - name: basic
              variants:
                  - suffix: "_fast"
                    plusargs: ["FAST_MODE=1", "DELAY=50"] # No need for '+'s
                    count: 10
                  - suffix: "_slow"
                    plusargs: ["FAST_MODE=0", "DELAY=200"] # No need for '+'s
                    count: 10
            - name: stress
              count: 8
              plusargs: ["DELAY=500"]
            - load
            - updown:7
